const std::string HelpMessage = 
"\n"
"To archive your files use command:\n"
"\n"
"cmd: archiver -c <archive_name> file1, [file2, ...]\n"
"\n"
"where file1, file2, ... - files you want to archiver.\n"
"\n"
"\n"
"\n"
"To unzip your archive use command:\n"
"\n"
"cmd: archiver -d <archive_name>\n"
"\n"
"This command will decode you archive <archive_name> and save files into current directory"
"\n"
"\n"
"\n"
"To get help you can use command:\n"
"\n"
"cmd: archiver -h";